### ISSUE TITLE
Cant skip CASClient::Frameworks::Rails::Filter

### ISSUE THREAD

**Issue by maxstudener** [rubycas/rubycas-client#54]
I have `before_filter CASClient::Frameworks::Rails::Filter` in my application controller and can't skip it in my an ajax call in another controller using `skip_before_filter CASClient::Frameworks::Rails::Filter`.

**Comment by thiyagarajanth** [comment]
Am using rails3.2.19, skip_before_filter CASClient::Frameworks::Rails::Filter and skip_filter CASClient::Frameworks::Rails::Filter not working
