### ISSUE TITLE
Single sign out doesn't destroy session

### ISSUE THREAD

**Issue by cthielen** [rubycas/rubycas-client#75]
Is there something special to do so that single sign out destroys the session hash? I've written support for single sign out into my application and can confirm it's being handled by my application in the logs but it doesn't seem to destroy the user's associated session hash.

Is it supposed to? How does one check that a CAS session has been expired via the single sign out?

**Comment by tydaniel** [comment]
I want to apply Rubycas-client with Bitnami Redmine.
But Single sign out doesn't work.
I just did all of steps according to README.
Error Log shows;

NoMethodError (undefined method `session_class' for ActiveRecord::SessionStore:Module):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

I don't know how to set the session class into redmine.
